/**
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NEW COLOR ®
 */
public class DashBoardTelaAdm extends javax.swing.JFrame {

    /**
     * Creates new form DashBoardTela
     */
    public DashBoardTelaAdm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashBoardPanel = new javax.swing.JPanel();
        sairButton = new javax.swing.JButton();
        cadastroDeNovosAdministradoresButton = new javax.swing.JButton();
        cadastroDeNovosAtendentesButton = new javax.swing.JButton();
        relatorioVacinacaoButton = new javax.swing.JButton();
        remoçãoDeAdministradorButton = new javax.swing.JButton();
        remocaoDeAtendenteButton = new javax.swing.JButton();
        cadastroDePessoasButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        dashBoardPanel.setBackground(new java.awt.Color(204, 255, 255));
        dashBoardPanel.setPreferredSize(new java.awt.Dimension(882, 561));

        sairButton.setText("Sair");
        sairButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sairButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        cadastroDeNovosAdministradoresButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mathe\\Desktop\\@@PROJETO DE MODELAGEM - A3@@\\ImagensProjetos\\icons8-administrador-masculino-48.png")); // NOI18N
        cadastroDeNovosAdministradoresButton.setText("Cadastro de novos administradores");
        cadastroDeNovosAdministradoresButton.setToolTipText("Cadastra novos administradores");
        cadastroDeNovosAdministradoresButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cadastroDeNovosAdministradoresButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastroDeNovosAdministradoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroDeNovosAdministradoresButtonActionPerformed(evt);
            }
        });

        cadastroDeNovosAtendentesButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mathe\\Desktop\\@@PROJETO DE MODELAGEM - A3@@\\ImagensProjetos\\icons8-recepção-48.png")); // NOI18N
        cadastroDeNovosAtendentesButton.setText("Cadastro de novos atendentes");
        cadastroDeNovosAtendentesButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cadastroDeNovosAtendentesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastroDeNovosAtendentesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroDeNovosAtendentesButtonActionPerformed(evt);
            }
        });

        relatorioVacinacaoButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mathe\\Desktop\\@@PROJETO DE MODELAGEM - A3@@\\ImagensProjetos\\icons8-caderno-48.png")); // NOI18N
        relatorioVacinacaoButton.setText("Relatório de vacinação");
        relatorioVacinacaoButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        relatorioVacinacaoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        relatorioVacinacaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioVacinacaoButtonActionPerformed(evt);
            }
        });

        remoçãoDeAdministradorButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mathe\\Desktop\\@@PROJETO DE MODELAGEM - A3@@\\ImagensProjetos\\icons8-lixeira-vazia-48.png")); // NOI18N
        remoçãoDeAdministradorButton.setText("Remoção de administradores ");
        remoçãoDeAdministradorButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        remoçãoDeAdministradorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        remoçãoDeAdministradorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remoçãoDeAdministradorButtonActionPerformed(evt);
            }
        });

        remocaoDeAtendenteButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mathe\\Desktop\\@@PROJETO DE MODELAGEM - A3@@\\ImagensProjetos\\icons8-lixeira-vazia-48.png")); // NOI18N
        remocaoDeAtendenteButton.setText("Remoção de atendente");
        remocaoDeAtendenteButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        remocaoDeAtendenteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        remocaoDeAtendenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remocaoDeAtendenteButtonActionPerformed(evt);
            }
        });

        cadastroDePessoasButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mathe\\Desktop\\@@PROJETO DE MODELAGEM - A3@@\\ImagensProjetos\\icons8-administrador-masculino-48.png")); // NOI18N
        cadastroDePessoasButton1.setText("Cadastro de pessoas a serem vacinadas");
        cadastroDePessoasButton1.setToolTipText("Cadastra novos administradores");
        cadastroDePessoasButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cadastroDePessoasButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastroDePessoasButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroDePessoasButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashBoardPanelLayout = new javax.swing.GroupLayout(dashBoardPanel);
        dashBoardPanel.setLayout(dashBoardPanelLayout);
        dashBoardPanelLayout.setHorizontalGroup(
            dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashBoardPanelLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cadastroDePessoasButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(remocaoDeAtendenteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                        .addComponent(cadastroDeNovosAtendentesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(relatorioVacinacaoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastroDeNovosAdministradoresButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(remoçãoDeAdministradorButton, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        dashBoardPanelLayout.setVerticalGroup(
            dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashBoardPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(cadastroDeNovosAdministradoresButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(cadastroDePessoasButton1)
                .addGap(18, 18, 18)
                .addComponent(cadastroDeNovosAtendentesButton)
                .addGap(18, 18, 18)
                .addComponent(relatorioVacinacaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(remoçãoDeAdministradorButton)
                .addGap(28, 28, 28)
                .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashBoardPanelLayout.createSequentialGroup()
                        .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashBoardPanelLayout.createSequentialGroup()
                        .addComponent(remocaoDeAtendenteButton)
                        .addGap(58, 58, 58))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashBoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashBoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroDeNovosAdministradoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroDeNovosAdministradoresButtonActionPerformed
        // TODO add your handling code here:
        CadastrarAdm cdm = new CadastrarAdm ();
        cdm.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_cadastroDeNovosAdministradoresButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_sairButtonActionPerformed

    private void cadastroDeNovosAtendentesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroDeNovosAtendentesButtonActionPerformed
        // TODO add your handling code here:
        CadastrarAtd cadt = new CadastrarAtd ();
        cadt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadastroDeNovosAtendentesButtonActionPerformed

    private void remoçãoDeAdministradorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remoçãoDeAdministradorButtonActionPerformed
        // TODO add your handling code here:
        RemocaoAdm rAtdAdm = new RemocaoAdm ();
        rAtdAdm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_remoçãoDeAdministradorButtonActionPerformed

    private void relatorioVacinacaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioVacinacaoButtonActionPerformed
        // TODO add your handling code here:
        Relatorio rl = new Relatorio();
        rl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_relatorioVacinacaoButtonActionPerformed

    private void remocaoDeAtendenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remocaoDeAtendenteButtonActionPerformed
        // TODO add your handling code here:
        RemocaoAtd rAtd = new RemocaoAtd ();
        rAtd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_remocaoDeAtendenteButtonActionPerformed

    private void cadastroDePessoasButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroDePessoasButton1ActionPerformed
        // TODO add your handling code here:
        CadastroPessoas cp = new CadastroPessoas ();
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadastroDePessoasButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoardTelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoardTelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoardTelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoardTelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoardTelaAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroDeNovosAdministradoresButton;
    private javax.swing.JButton cadastroDeNovosAtendentesButton;
    private javax.swing.JButton cadastroDePessoasButton1;
    private javax.swing.JPanel dashBoardPanel;
    private javax.swing.JButton relatorioVacinacaoButton;
    private javax.swing.JButton remocaoDeAtendenteButton;
    private javax.swing.JButton remoçãoDeAdministradorButton;
    private javax.swing.JButton sairButton;
    // End of variables declaration//GEN-END:variables
}
